name: Check Optional Dependencies

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install flake8 pytest black
    - name: Run Base Install
      run: |
        python -m pip install -e ".[base]"
    - name: Run Checks
      run: |
        python tests/check_pip.py missing tensorflow ivis opentsne
        python tests/check_pip.py contains spacy
        python -c "from whatlies.language import SpacyLanguage"
        python -c "from whatlies.transformers import Pca"
    - name: Install Tensorflow Dependencies
      run: |
        python -m pip install -e ".[tfhub]"
    - name: Run Checks
      run: |
        python tests/check_pip.py missing ivis opentsne
        python tests/check_pip.py contains spacy tensorflow
        python -c "from whatlies.transformers import Pca"
    - name: Install IVIS
      run: |
        python -m pip install -e ".[ivis]"
    - name: Run Checks
      run: |
        python tests/check_pip.py missing opentsne
        python tests/check_pip.py contains spacy tensorflow ivis
    - name: Install All
      run: |
        python -m pip install -e ".[all]"
    - name: Run Checks
      run: |
        python tests/check_pip.py contains spacy tensorflow ivis opentsne transformers
    - name: Docs can Build
      run: |
        python -m pip install -e ".[docs]"
        mkdocs build
